/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Answer {
  'answer' : { 'multipleChoice' : bigint } |
    { 'trueFalse' : boolean },
  'questionId' : bigint,
}
export type AssignedRank = string;
export interface ChatMessage {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export interface Comment {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
  'postId' : bigint,
}
export interface ConversationSummary {
  'lastMessage' : string,
  'otherUser' : Principal,
  'unreadCount' : bigint,
  'lastTimestamp' : Time,
}
export interface CustomGame {
  'id' : bigint,
  'title' : string,
  'creator' : Principal,
  'gameType' : {
      'customSpinWheel' : { 'segments' : Array<SpinWheelSegment> }
    } |
    { 'customTrivia' : { 'questions' : Array<CustomTriviaQuestion> } },
}
export interface CustomTriviaQuestion {
  'correctOption' : bigint,
  'text' : string,
  'options' : Array<string>,
  'pointsReward' : bigint,
}
export interface PlayerRankEntry { 'player' : Principal, 'rank' : AssignedRank }
export interface PointPackage {
  'id' : bigint,
  'name' : string,
  'priceInPaise' : bigint,
  'points' : bigint,
}
export interface PointsEntry { 'player' : Principal, 'points' : bigint }
export interface Post {
  'id' : bigint,
  'author' : Principal,
  'message' : string,
  'timestamp' : Time,
  'quizId' : bigint,
}
export interface PostWithComment { 'post' : Post, 'comments' : Array<Comment> }
export interface PostWithStats {
  'likeCount' : bigint,
  'post' : Post,
  'commentCount' : bigint,
}
export interface PrivateMessage {
  'id' : bigint,
  'content' : string,
  'recipient' : Principal,
  'isRead' : boolean,
  'sender' : Principal,
  'timestamp' : Time,
}
export interface Question {
  'id' : bigint,
  'text' : string,
  'questionType' : {
      'multipleChoice' : { 'correctOption' : bigint, 'options' : Array<string> }
    } |
    { 'trueFalse' : { 'correctAnswer' : boolean } },
  'quizId' : bigint,
}
export interface Quiz {
  'id' : bigint,
  'title' : string,
  'creator' : Principal,
  'description' : string,
  'timestamp' : Time,
}
export interface QuizStats {
  'title' : string,
  'totalAttemptCount' : bigint,
  'quizId' : bigint,
  'totalCorrectCount' : bigint,
}
export interface QuizWithAnswers {
  'quiz' : Quiz,
  'questions' : Array<Question>,
}
export interface Result {
  'username' : string,
  'player' : Principal,
  'score' : bigint,
  'totalQuestions' : bigint,
  'timestamp' : Time,
  'quizId' : bigint,
}
export interface SpinWheelSegment { 'segmentLabel' : string, 'points' : bigint }
export type Time = bigint;
export interface UserProfile { 'username' : string, 'isVip' : boolean }
export interface _SERVICE {
  'addComment' : ActorMethod<[bigint, string], bigint>,
  'addQuestion' : ActorMethod<[bigint, Question], bigint>,
  'assignCallerUserRole' : ActorMethod<[], undefined>,
  'assignPlayerRank' : ActorMethod<[Principal, AssignedRank], undefined>,
  'awardPoints' : ActorMethod<[bigint], undefined>,
  'banPlayer' : ActorMethod<[Principal], undefined>,
  'claimDailyChest' : ActorMethod<[], bigint>,
  'claimLuckyStar' : ActorMethod<[], bigint>,
  'claimMysteryBonus' : ActorMethod<[], bigint>,
  'createCustomSpinWheel' : ActorMethod<
    [string, Array<SpinWheelSegment>],
    bigint
  >,
  'createCustomTrivia' : ActorMethod<
    [string, Array<CustomTriviaQuestion>],
    bigint
  >,
  'createPost' : ActorMethod<[bigint, string], bigint>,
  'createQuiz' : ActorMethod<[string, string], bigint>,
  'createUserProfile' : ActorMethod<[string], undefined>,
  'deductPoints' : ActorMethod<[Principal, bigint], bigint>,
  'deleteQuiz' : ActorMethod<[bigint], undefined>,
  'fulfillPointsPurchase' : ActorMethod<[bigint, string], bigint>,
  'getAdminQuizAnswers' : ActorMethod<[], Array<QuizWithAnswers>>,
  'getAllAssignedRanks' : ActorMethod<[], Array<PlayerRankEntry>>,
  'getAllCustomGames' : ActorMethod<[], Array<CustomGame>>,
  'getAllPlayerPoints' : ActorMethod<[], Array<PointsEntry>>,
  'getAllPostsWithStats' : ActorMethod<[], Array<PostWithStats>>,
  'getAllQuizzes' : ActorMethod<[], Array<Quiz>>,
  'getBannedPlayers' : ActorMethod<[], Array<Principal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], string>,
  'getCommentsByPostId' : ActorMethod<[bigint], Array<Comment>>,
  'getConversation' : ActorMethod<[Principal], Array<PrivateMessage>>,
  'getDailyChestCooldown' : ActorMethod<[], [] | [Time]>,
  'getLuckyStarCooldown' : ActorMethod<[], [] | [Time]>,
  'getMemoryGameCooldown' : ActorMethod<[], [] | [Time]>,
  'getMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getMonthlyLimit' : ActorMethod<[], bigint>,
  'getMyConversations' : ActorMethod<[], Array<ConversationSummary>>,
  'getMyMonthlySpend' : ActorMethod<[], bigint>,
  'getMyPoints' : ActorMethod<[], bigint>,
  'getMysteryBonusCooldown' : ActorMethod<[], [] | [Time]>,
  'getOwner' : ActorMethod<[], Principal>,
  'getPlayerAssignedRank' : ActorMethod<[Principal], [] | [AssignedRank]>,
  'getPointPackages' : ActorMethod<[], Array<PointPackage>>,
  'getPostWithComments' : ActorMethod<[bigint], [] | [PostWithComment]>,
  'getPostsByQuizId' : ActorMethod<[bigint], Array<PostWithStats>>,
  'getQuiz' : ActorMethod<[bigint], Quiz>,
  'getQuizLeaderboard' : ActorMethod<[bigint], [] | [Array<Result>]>,
  'getQuizQuestions' : ActorMethod<[bigint], Array<Question>>,
  'getQuizStats' : ActorMethod<[], Array<QuizStats>>,
  'getSpinWheelCooldown' : ActorMethod<[], [] | [Time]>,
  'getTopPlayer' : ActorMethod<[], [] | [Principal]>,
  'getTotalVisitors' : ActorMethod<[], bigint>,
  'getTrollCooldown' : ActorMethod<[Principal], [] | [Time]>,
  'getUnreadMessageCount' : ActorMethod<[], bigint>,
  'getUserPosts' : ActorMethod<[Principal], Array<PostWithStats>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserQuizResults' : ActorMethod<[], Array<Result>>,
  'giftPoints' : ActorMethod<[Principal, bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerBanned' : ActorMethod<[], boolean>,
  'isCallerOwner' : ActorMethod<[], boolean>,
  'isPlayerBanned' : ActorMethod<[Principal], boolean>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'markConversationRead' : ActorMethod<[Principal], undefined>,
  'playCustomSpinWheel' : ActorMethod<[bigint], bigint>,
  'playCustomTrivia' : ActorMethod<
    [bigint, Array<{ 'answerIndex' : bigint, 'questionId' : bigint }>],
    bigint
  >,
  'purchaseVip' : ActorMethod<[], undefined>,
  'recordMemoryGamePlay' : ActorMethod<[], undefined>,
  'recordSpinWheelPlay' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchUsers' : ActorMethod<[string], Array<[Principal, UserProfile]>>,
  'sendMessage' : ActorMethod<[string], bigint>,
  'sendPrivateMessage' : ActorMethod<[Principal, string], bigint>,
  'submitQuizAnswers' : ActorMethod<[bigint, Array<Answer>], bigint>,
  'trackVisit' : ActorMethod<[], undefined>,
  'trollPlayer' : ActorMethod<[Principal], bigint>,
  'unbanPlayer' : ActorMethod<[Principal], undefined>,
  'unlikePost' : ActorMethod<[bigint], undefined>,
  'updateUserProfile' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];