/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
  'postId' : bigint,
}
export interface PointsEntry { 'player' : Principal, 'points' : bigint }
export interface Post {
  'id' : bigint,
  'author' : Principal,
  'message' : string,
  'timestamp' : Time,
  'quizId' : bigint,
}
export interface PostWithComment { 'post' : Post, 'comments' : Array<Comment> }
export interface PostWithStats {
  'likeCount' : bigint,
  'post' : Post,
  'commentCount' : bigint,
}
export interface Question {
  'id' : bigint,
  'text' : string,
  'questionType' : {
      'multipleChoice' : { 'correctOption' : bigint, 'options' : Array<string> }
    } |
    { 'trueFalse' : { 'correctAnswer' : boolean } },
  'quizId' : bigint,
}
export interface Quiz {
  'id' : bigint,
  'title' : string,
  'creator' : Principal,
  'description' : string,
  'timestamp' : Time,
}
export interface QuizStats {
  'title' : string,
  'totalAttemptCount' : bigint,
  'quizId' : bigint,
  'totalCorrectCount' : bigint,
}
export interface QuizWithAnswers {
  'quiz' : Quiz,
  'questions' : Array<Question>,
}
export interface Result {
  'username' : string,
  'player' : Principal,
  'score' : bigint,
  'totalQuestions' : bigint,
  'timestamp' : Time,
  'quizId' : bigint,
}
export interface T {
  'answer' : { 'multipleChoice' : bigint } |
    { 'trueFalse' : boolean },
  'questionId' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'username' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string], bigint>,
  'addQuestion' : ActorMethod<[bigint, Question], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'awardPoints' : ActorMethod<[bigint], undefined>,
  'createPost' : ActorMethod<[bigint, string], bigint>,
  'createQuiz' : ActorMethod<[string, string], bigint>,
  'createUserProfile' : ActorMethod<[string], undefined>,
  'getAdminQuizAnswers' : ActorMethod<[], Array<QuizWithAnswers>>,
  'getAllPlayerPoints' : ActorMethod<[], Array<PointsEntry>>,
  'getAllPostsWithStats' : ActorMethod<[], Array<PostWithStats>>,
  'getAllQuizzes' : ActorMethod<[], Array<Quiz>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentsByPostId' : ActorMethod<[bigint], Array<Comment>>,
  'getMyPoints' : ActorMethod<[], bigint>,
  'getPostWithComments' : ActorMethod<[bigint], [] | [PostWithComment]>,
  'getPostsByQuizId' : ActorMethod<[bigint], Array<PostWithStats>>,
  'getQuiz' : ActorMethod<[bigint], Quiz>,
  'getQuizLeaderboard' : ActorMethod<[bigint], [] | [Array<Result>]>,
  'getQuizQuestions' : ActorMethod<[bigint], Array<Question>>,
  'getQuizStats' : ActorMethod<[], Array<QuizStats>>,
  'getTopPlayer' : ActorMethod<[], [] | [Principal]>,
  'getUserPosts' : ActorMethod<[Principal], Array<PostWithStats>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserQuizResults' : ActorMethod<[], Array<Result>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitQuizAnswers' : ActorMethod<[bigint, Array<T>], bigint>,
  'unlikePost' : ActorMethod<[bigint], undefined>,
  'updateUserProfile' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];