/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Question = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'questionType' : IDL.Variant({
    'multipleChoice' : IDL.Record({
      'correctOption' : IDL.Nat,
      'options' : IDL.Vec(IDL.Text),
    }),
    'trueFalse' : IDL.Record({ 'correctAnswer' : IDL.Bool }),
  }),
  'quizId' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'author' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : Time,
  'quizId' : IDL.Nat,
});
export const PostWithStats = IDL.Record({
  'likeCount' : IDL.Nat,
  'post' : Post,
  'commentCount' : IDL.Nat,
});
export const Quiz = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({ 'username' : IDL.Text });
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'postId' : IDL.Nat,
});
export const PostWithComment = IDL.Record({
  'post' : Post,
  'comments' : IDL.Vec(Comment),
});
export const Result = IDL.Record({
  'username' : IDL.Text,
  'player' : IDL.Principal,
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'timestamp' : Time,
  'quizId' : IDL.Nat,
});
export const QuizStats = IDL.Record({
  'title' : IDL.Text,
  'totalAttemptCount' : IDL.Nat,
  'quizId' : IDL.Nat,
  'totalCorrectCount' : IDL.Nat,
});
export const T = IDL.Record({
  'answer' : IDL.Variant({
    'multipleChoice' : IDL.Nat,
    'trueFalse' : IDL.Bool,
  }),
  'questionId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'addQuestion' : IDL.Func([IDL.Nat, Question], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'createQuiz' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createUserProfile' : IDL.Func([IDL.Text], [], []),
  'getAllPostsWithStats' : IDL.Func([], [IDL.Vec(PostWithStats)], ['query']),
  'getAllQuizzes' : IDL.Func([], [IDL.Vec(Quiz)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentsByPostId' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getPostWithComments' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(PostWithComment)],
      ['query'],
    ),
  'getPostsByQuizId' : IDL.Func([IDL.Nat], [IDL.Vec(PostWithStats)], ['query']),
  'getQuiz' : IDL.Func([IDL.Nat], [Quiz], ['query']),
  'getQuizLeaderboard' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IDL.Vec(Result))],
      ['query'],
    ),
  'getQuizQuestions' : IDL.Func([IDL.Nat], [IDL.Vec(Question)], ['query']),
  'getQuizStats' : IDL.Func([], [IDL.Vec(QuizStats)], ['query']),
  'getUserPosts' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PostWithStats)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserQuizResults' : IDL.Func([], [IDL.Vec(Result)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitQuizAnswers' : IDL.Func([IDL.Nat, IDL.Vec(T)], [IDL.Nat], []),
  'unlikePost' : IDL.Func([IDL.Nat], [], []),
  'updateUserProfile' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'questionType' : IDL.Variant({
      'multipleChoice' : IDL.Record({
        'correctOption' : IDL.Nat,
        'options' : IDL.Vec(IDL.Text),
      }),
      'trueFalse' : IDL.Record({ 'correctAnswer' : IDL.Bool }),
    }),
    'quizId' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'author' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : Time,
    'quizId' : IDL.Nat,
  });
  const PostWithStats = IDL.Record({
    'likeCount' : IDL.Nat,
    'post' : Post,
    'commentCount' : IDL.Nat,
  });
  const Quiz = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({ 'username' : IDL.Text });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'postId' : IDL.Nat,
  });
  const PostWithComment = IDL.Record({
    'post' : Post,
    'comments' : IDL.Vec(Comment),
  });
  const Result = IDL.Record({
    'username' : IDL.Text,
    'player' : IDL.Principal,
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'timestamp' : Time,
    'quizId' : IDL.Nat,
  });
  const QuizStats = IDL.Record({
    'title' : IDL.Text,
    'totalAttemptCount' : IDL.Nat,
    'quizId' : IDL.Nat,
    'totalCorrectCount' : IDL.Nat,
  });
  const T = IDL.Record({
    'answer' : IDL.Variant({
      'multipleChoice' : IDL.Nat,
      'trueFalse' : IDL.Bool,
    }),
    'questionId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'addQuestion' : IDL.Func([IDL.Nat, Question], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'createQuiz' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createUserProfile' : IDL.Func([IDL.Text], [], []),
    'getAllPostsWithStats' : IDL.Func([], [IDL.Vec(PostWithStats)], ['query']),
    'getAllQuizzes' : IDL.Func([], [IDL.Vec(Quiz)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentsByPostId' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getPostWithComments' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PostWithComment)],
        ['query'],
      ),
    'getPostsByQuizId' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PostWithStats)],
        ['query'],
      ),
    'getQuiz' : IDL.Func([IDL.Nat], [Quiz], ['query']),
    'getQuizLeaderboard' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Vec(Result))],
        ['query'],
      ),
    'getQuizQuestions' : IDL.Func([IDL.Nat], [IDL.Vec(Question)], ['query']),
    'getQuizStats' : IDL.Func([], [IDL.Vec(QuizStats)], ['query']),
    'getUserPosts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PostWithStats)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserQuizResults' : IDL.Func([], [IDL.Vec(Result)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitQuizAnswers' : IDL.Func([IDL.Nat, IDL.Vec(T)], [IDL.Nat], []),
    'unlikePost' : IDL.Func([IDL.Nat], [], []),
    'updateUserProfile' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };