/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Comment {
    id: bigint;
    content: string;
    author: Principal;
    timestamp: Time;
    postId: bigint;
}
export interface SpinWheelSegment {
    segmentLabel: string;
    points: bigint;
}
export interface PointsEntry {
    player: Principal;
    points: bigint;
}
export interface Quiz {
    id: bigint;
    title: string;
    creator: Principal;
    description: string;
    timestamp: Time;
}
export interface QuizStats {
    title: string;
    totalAttemptCount: bigint;
    quizId: bigint;
    totalCorrectCount: bigint;
}
export interface CustomTriviaQuestion {
    correctOption: bigint;
    text: string;
    options: Array<string>;
    pointsReward: bigint;
}
export interface CustomGame {
    id: bigint;
    title: string;
    creator: Principal;
    gameType: {
        __kind__: "customSpinWheel";
        customSpinWheel: {
            segments: Array<SpinWheelSegment>;
        };
    } | {
        __kind__: "customTrivia";
        customTrivia: {
            questions: Array<CustomTriviaQuestion>;
        };
    };
}
export interface PrivateMessage {
    id: bigint;
    content: string;
    recipient: Principal;
    isRead: boolean;
    sender: Principal;
    timestamp: Time;
}
export type AssignedRank = string;
export interface Result {
    username: string;
    player: Principal;
    score: bigint;
    totalQuestions: bigint;
    timestamp: Time;
    quizId: bigint;
}
export interface QuizWithAnswers {
    quiz: Quiz;
    questions: Array<Question>;
}
export interface PostWithStats {
    likeCount: bigint;
    post: Post;
    commentCount: bigint;
}
export interface PostWithComment {
    post: Post;
    comments: Array<Comment>;
}
export interface Post {
    id: bigint;
    author: Principal;
    message: string;
    timestamp: Time;
    quizId: bigint;
}
export interface PlayerRankEntry {
    player: Principal;
    rank: AssignedRank;
}
export interface ChatMessage {
    id: bigint;
    content: string;
    author: Principal;
    timestamp: Time;
}
export interface Answer {
    answer: {
        __kind__: "multipleChoice";
        multipleChoice: bigint;
    } | {
        __kind__: "trueFalse";
        trueFalse: boolean;
    };
    questionId: bigint;
}
export interface Question {
    id: bigint;
    text: string;
    questionType: {
        __kind__: "multipleChoice";
        multipleChoice: {
            correctOption: bigint;
            options: Array<string>;
        };
    } | {
        __kind__: "trueFalse";
        trueFalse: {
            correctAnswer: boolean;
        };
    };
    quizId: bigint;
}
export interface ConversationSummary {
    lastMessage: string;
    otherUser: Principal;
    unreadCount: bigint;
    lastTimestamp: Time;
}
export interface PointPackage {
    id: bigint;
    name: string;
    priceInPaise: bigint;
    points: bigint;
}
export interface UserProfile {
    username: string;
    isVip: boolean;
}
export interface backendInterface {
    addComment(postId: bigint, content: string): Promise<bigint>;
    addQuestion(quizId: bigint, question: Question): Promise<bigint>;
    assignCallerUserRole(): Promise<void>;
    assignPlayerRank(player: Principal, rank: AssignedRank): Promise<void>;
    awardPoints(amount: bigint): Promise<void>;
    banPlayer(player: Principal): Promise<void>;
    claimDailyChest(): Promise<bigint>;
    claimLuckyStar(): Promise<bigint>;
    claimMysteryBonus(): Promise<bigint>;
    createCustomSpinWheel(title: string, segments: Array<SpinWheelSegment>): Promise<bigint>;
    createCustomTrivia(title: string, qs: Array<CustomTriviaQuestion>): Promise<bigint>;
    createPost(quizId: bigint, message: string): Promise<bigint>;
    createQuiz(title: string, description: string): Promise<bigint>;
    createUserProfile(username: string): Promise<void>;
    deductPoints(player: Principal, amount: bigint): Promise<bigint>;
    deleteQuiz(quizId: bigint): Promise<void>;
    fulfillPointsPurchase(packageId: bigint, sessionId: string): Promise<bigint>;
    getAdminQuizAnswers(): Promise<Array<QuizWithAnswers>>;
    getAllAssignedRanks(): Promise<Array<PlayerRankEntry>>;
    getAllCustomGames(): Promise<Array<CustomGame>>;
    getAllPlayerPoints(): Promise<Array<PointsEntry>>;
    getAllPostsWithStats(): Promise<Array<PostWithStats>>;
    getAllQuizzes(): Promise<Array<Quiz>>;
    getBannedPlayers(): Promise<Array<Principal>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<string>;
    getCommentsByPostId(postId: bigint): Promise<Array<Comment>>;
    getConversation(otherUser: Principal): Promise<Array<PrivateMessage>>;
    getDailyChestCooldown(): Promise<Time | null>;
    getLuckyStarCooldown(): Promise<Time | null>;
    getMemoryGameCooldown(): Promise<Time | null>;
    getMessages(): Promise<Array<ChatMessage>>;
    getMonthlyLimit(): Promise<bigint>;
    getMyConversations(): Promise<Array<ConversationSummary>>;
    getMyMonthlySpend(): Promise<bigint>;
    getMyPoints(): Promise<bigint>;
    getMysteryBonusCooldown(): Promise<Time | null>;
    getOwner(): Promise<Principal>;
    getPlayerAssignedRank(player: Principal): Promise<AssignedRank | null>;
    getPointPackages(): Promise<Array<PointPackage>>;
    getPostWithComments(postId: bigint): Promise<PostWithComment | null>;
    getPostsByQuizId(quizId: bigint): Promise<Array<PostWithStats>>;
    getQuiz(quizId: bigint): Promise<Quiz>;
    getQuizLeaderboard(quizId: bigint): Promise<Array<Result> | null>;
    getQuizQuestions(quizId: bigint): Promise<Array<Question>>;
    getQuizStats(): Promise<Array<QuizStats>>;
    getSpinWheelCooldown(): Promise<Time | null>;
    getTopPlayer(): Promise<Principal | null>;
    getTotalVisitors(): Promise<bigint>;
    getTrollCooldown(target: Principal): Promise<Time | null>;
    getUnreadMessageCount(): Promise<bigint>;
    getUserPosts(user: Principal): Promise<Array<PostWithStats>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserQuizResults(): Promise<Array<Result>>;
    giftPoints(recipient: Principal, amount: bigint): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isCallerBanned(): Promise<boolean>;
    isCallerOwner(): Promise<boolean>;
    isPlayerBanned(player: Principal): Promise<boolean>;
    likePost(postId: bigint): Promise<void>;
    markConversationRead(otherUser: Principal): Promise<void>;
    playCustomSpinWheel(gameId: bigint): Promise<bigint>;
    playCustomTrivia(gameId: bigint, answers: Array<{
        answerIndex: bigint;
        questionId: bigint;
    }>): Promise<bigint>;
    purchaseVip(): Promise<void>;
    recordMemoryGamePlay(): Promise<void>;
    recordSpinWheelPlay(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchUsers(searchQuery: string): Promise<Array<[Principal, UserProfile]>>;
    sendMessage(content: string): Promise<bigint>;
    sendPrivateMessage(recipient: Principal, content: string): Promise<bigint>;
    submitQuizAnswers(quizId: bigint, answers: Array<Answer>): Promise<bigint>;
    trackVisit(): Promise<void>;
    trollPlayer(target: Principal): Promise<bigint>;
    unbanPlayer(player: Principal): Promise<void>;
    unlikePost(postId: bigint): Promise<void>;
    updateUserProfile(username: string): Promise<void>;
}
import type { Answer as _Answer, AssignedRank as _AssignedRank, CustomGame as _CustomGame, CustomTriviaQuestion as _CustomTriviaQuestion, PostWithComment as _PostWithComment, Question as _Question, Quiz as _Quiz, QuizWithAnswers as _QuizWithAnswers, Result as _Result, SpinWheelSegment as _SpinWheelSegment, Time as _Time, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addComment(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async addQuestion(arg0: bigint, arg1: Question): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuestion(arg0, to_candid_Question_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuestion(arg0, to_candid_Question_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole();
            return result;
        }
    }
    async assignPlayerRank(arg0: Principal, arg1: AssignedRank): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignPlayerRank(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignPlayerRank(arg0, arg1);
            return result;
        }
    }
    async awardPoints(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.awardPoints(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.awardPoints(arg0);
            return result;
        }
    }
    async banPlayer(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.banPlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.banPlayer(arg0);
            return result;
        }
    }
    async claimDailyChest(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.claimDailyChest();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimDailyChest();
            return result;
        }
    }
    async claimLuckyStar(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.claimLuckyStar();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimLuckyStar();
            return result;
        }
    }
    async claimMysteryBonus(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.claimMysteryBonus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimMysteryBonus();
            return result;
        }
    }
    async createCustomSpinWheel(arg0: string, arg1: Array<SpinWheelSegment>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomSpinWheel(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomSpinWheel(arg0, arg1);
            return result;
        }
    }
    async createCustomTrivia(arg0: string, arg1: Array<CustomTriviaQuestion>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomTrivia(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomTrivia(arg0, arg1);
            return result;
        }
    }
    async createPost(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, arg1);
            return result;
        }
    }
    async createQuiz(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuiz(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuiz(arg0, arg1);
            return result;
        }
    }
    async createUserProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserProfile(arg0);
            return result;
        }
    }
    async deductPoints(arg0: Principal, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.deductPoints(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deductPoints(arg0, arg1);
            return result;
        }
    }
    async deleteQuiz(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuiz(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuiz(arg0);
            return result;
        }
    }
    async fulfillPointsPurchase(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.fulfillPointsPurchase(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fulfillPointsPurchase(arg0, arg1);
            return result;
        }
    }
    async getAdminQuizAnswers(): Promise<Array<QuizWithAnswers>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminQuizAnswers();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminQuizAnswers();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAssignedRanks(): Promise<Array<PlayerRankEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssignedRanks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssignedRanks();
            return result;
        }
    }
    async getAllCustomGames(): Promise<Array<CustomGame>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomGames();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomGames();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPlayerPoints(): Promise<Array<PointsEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlayerPoints();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlayerPoints();
            return result;
        }
    }
    async getAllPostsWithStats(): Promise<Array<PostWithStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPostsWithStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPostsWithStats();
            return result;
        }
    }
    async getAllQuizzes(): Promise<Array<Quiz>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuizzes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuizzes();
            return result;
        }
    }
    async getBannedPlayers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBannedPlayers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBannedPlayers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return result;
        }
    }
    async getCommentsByPostId(arg0: bigint): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommentsByPostId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommentsByPostId(arg0);
            return result;
        }
    }
    async getConversation(arg0: Principal): Promise<Array<PrivateMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return result;
        }
    }
    async getDailyChestCooldown(): Promise<Time | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyChestCooldown();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyChestCooldown();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLuckyStarCooldown(): Promise<Time | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLuckyStarCooldown();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLuckyStarCooldown();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMemoryGameCooldown(): Promise<Time | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemoryGameCooldown();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemoryGameCooldown();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages();
            return result;
        }
    }
    async getMonthlyLimit(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyLimit();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyLimit();
            return result;
        }
    }
    async getMyConversations(): Promise<Array<ConversationSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyConversations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyConversations();
            return result;
        }
    }
    async getMyMonthlySpend(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMonthlySpend();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMonthlySpend();
            return result;
        }
    }
    async getMyPoints(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPoints();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPoints();
            return result;
        }
    }
    async getMysteryBonusCooldown(): Promise<Time | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMysteryBonusCooldown();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMysteryBonusCooldown();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwner(): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwner();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwner();
            return result;
        }
    }
    async getPlayerAssignedRank(arg0: Principal): Promise<AssignedRank | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerAssignedRank(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerAssignedRank(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPointPackages(): Promise<Array<PointPackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPointPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPointPackages();
            return result;
        }
    }
    async getPostWithComments(arg0: bigint): Promise<PostWithComment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostWithComments(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostWithComments(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPostsByQuizId(arg0: bigint): Promise<Array<PostWithStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostsByQuizId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostsByQuizId(arg0);
            return result;
        }
    }
    async getQuiz(arg0: bigint): Promise<Quiz> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuiz(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuiz(arg0);
            return result;
        }
    }
    async getQuizLeaderboard(arg0: bigint): Promise<Array<Result> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizLeaderboard(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizLeaderboard(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuizQuestions(arg0: bigint): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizQuestions(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizQuestions(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuizStats(): Promise<Array<QuizStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizStats();
            return result;
        }
    }
    async getSpinWheelCooldown(): Promise<Time | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpinWheelCooldown();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpinWheelCooldown();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopPlayer(): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopPlayer();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopPlayer();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalVisitors(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalVisitors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalVisitors();
            return result;
        }
    }
    async getTrollCooldown(arg0: Principal): Promise<Time | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrollCooldown(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrollCooldown(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadMessageCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadMessageCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadMessageCount();
            return result;
        }
    }
    async getUserPosts(arg0: Principal): Promise<Array<PostWithStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPosts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPosts(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserQuizResults(): Promise<Array<Result>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserQuizResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserQuizResults();
            return result;
        }
    }
    async giftPoints(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.giftPoints(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.giftPoints(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerBanned(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerBanned();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerBanned();
            return result;
        }
    }
    async isCallerOwner(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerOwner();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerOwner();
            return result;
        }
    }
    async isPlayerBanned(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isPlayerBanned(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isPlayerBanned(arg0);
            return result;
        }
    }
    async likePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async markConversationRead(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markConversationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markConversationRead(arg0);
            return result;
        }
    }
    async playCustomSpinWheel(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.playCustomSpinWheel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.playCustomSpinWheel(arg0);
            return result;
        }
    }
    async playCustomTrivia(arg0: bigint, arg1: Array<{
        answerIndex: bigint;
        questionId: bigint;
    }>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.playCustomTrivia(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.playCustomTrivia(arg0, arg1);
            return result;
        }
    }
    async purchaseVip(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseVip();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseVip();
            return result;
        }
    }
    async recordMemoryGamePlay(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordMemoryGamePlay();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordMemoryGamePlay();
            return result;
        }
    }
    async recordSpinWheelPlay(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSpinWheelPlay();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSpinWheelPlay();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchUsers(arg0: string): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchUsers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchUsers(arg0);
            return result;
        }
    }
    async sendMessage(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0);
            return result;
        }
    }
    async sendPrivateMessage(arg0: Principal, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendPrivateMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendPrivateMessage(arg0, arg1);
            return result;
        }
    }
    async submitQuizAnswers(arg0: bigint, arg1: Array<Answer>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuizAnswers(arg0, to_candid_vec_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuizAnswers(arg0, to_candid_vec_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async trackVisit(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.trackVisit();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackVisit();
            return result;
        }
    }
    async trollPlayer(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.trollPlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trollPlayer(arg0);
            return result;
        }
    }
    async unbanPlayer(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unbanPlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unbanPlayer(arg0);
            return result;
        }
    }
    async unlikePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikePost(arg0);
            return result;
        }
    }
    async updateUserProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_CustomGame_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomGame): CustomGame {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_QuizWithAnswers_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuizWithAnswers): QuizWithAnswers {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AssignedRank]): AssignedRank | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PostWithComment]): PostWithComment | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Result>]): Array<Result> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    creator: Principal;
    gameType: {
        customSpinWheel: {
            segments: Array<_SpinWheelSegment>;
        };
    } | {
        customTrivia: {
            questions: Array<_CustomTriviaQuestion>;
        };
    };
}): {
    id: bigint;
    title: string;
    creator: Principal;
    gameType: {
        __kind__: "customSpinWheel";
        customSpinWheel: {
            segments: Array<SpinWheelSegment>;
        };
    } | {
        __kind__: "customTrivia";
        customTrivia: {
            questions: Array<CustomTriviaQuestion>;
        };
    };
} {
    return {
        id: value.id,
        title: value.title,
        creator: value.creator,
        gameType: from_candid_variant_n14(_uploadFile, _downloadFile, value.gameType)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    quiz: _Quiz;
    questions: Array<_Question>;
}): {
    quiz: Quiz;
    questions: Array<Question>;
} {
    return {
        quiz: value.quiz,
        questions: from_candid_vec_n7(_uploadFile, _downloadFile, value.questions)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    text: string;
    questionType: {
        multipleChoice: {
            correctOption: bigint;
            options: Array<string>;
        };
    } | {
        trueFalse: {
            correctAnswer: boolean;
        };
    };
    quizId: bigint;
}): {
    id: bigint;
    text: string;
    questionType: {
        __kind__: "multipleChoice";
        multipleChoice: {
            correctOption: bigint;
            options: Array<string>;
        };
    } | {
        __kind__: "trueFalse";
        trueFalse: {
            correctAnswer: boolean;
        };
    };
    quizId: bigint;
} {
    return {
        id: value.id,
        text: value.text,
        questionType: from_candid_variant_n10(_uploadFile, _downloadFile, value.questionType),
        quizId: value.quizId
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    multipleChoice: {
        correctOption: bigint;
        options: Array<string>;
    };
} | {
    trueFalse: {
        correctAnswer: boolean;
    };
}): {
    __kind__: "multipleChoice";
    multipleChoice: {
        correctOption: bigint;
        options: Array<string>;
    };
} | {
    __kind__: "trueFalse";
    trueFalse: {
        correctAnswer: boolean;
    };
} {
    return "multipleChoice" in value ? {
        __kind__: "multipleChoice",
        multipleChoice: value.multipleChoice
    } : "trueFalse" in value ? {
        __kind__: "trueFalse",
        trueFalse: value.trueFalse
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customSpinWheel: {
        segments: Array<_SpinWheelSegment>;
    };
} | {
    customTrivia: {
        questions: Array<_CustomTriviaQuestion>;
    };
}): {
    __kind__: "customSpinWheel";
    customSpinWheel: {
        segments: Array<SpinWheelSegment>;
    };
} | {
    __kind__: "customTrivia";
    customTrivia: {
        questions: Array<CustomTriviaQuestion>;
    };
} {
    return "customSpinWheel" in value ? {
        __kind__: "customSpinWheel",
        customSpinWheel: value.customSpinWheel
    } : "customTrivia" in value ? {
        __kind__: "customTrivia",
        customTrivia: value.customTrivia
    } : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomGame>): Array<CustomGame> {
    return value.map((x)=>from_candid_CustomGame_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuizWithAnswers>): Array<QuizWithAnswers> {
    return value.map((x)=>from_candid_QuizWithAnswers_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Answer_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Answer): _Answer {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_Question_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Question): _Question {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    text: string;
    questionType: {
        __kind__: "multipleChoice";
        multipleChoice: {
            correctOption: bigint;
            options: Array<string>;
        };
    } | {
        __kind__: "trueFalse";
        trueFalse: {
            correctAnswer: boolean;
        };
    };
    quizId: bigint;
}): {
    id: bigint;
    text: string;
    questionType: {
        multipleChoice: {
            correctOption: bigint;
            options: Array<string>;
        };
    } | {
        trueFalse: {
            correctAnswer: boolean;
        };
    };
    quizId: bigint;
} {
    return {
        id: value.id,
        text: value.text,
        questionType: to_candid_variant_n3(_uploadFile, _downloadFile, value.questionType),
        quizId: value.quizId
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    answer: {
        __kind__: "multipleChoice";
        multipleChoice: bigint;
    } | {
        __kind__: "trueFalse";
        trueFalse: boolean;
    };
    questionId: bigint;
}): {
    answer: {
        multipleChoice: bigint;
    } | {
        trueFalse: boolean;
    };
    questionId: bigint;
} {
    return {
        answer: to_candid_variant_n24(_uploadFile, _downloadFile, value.answer),
        questionId: value.questionId
    };
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "multipleChoice";
    multipleChoice: bigint;
} | {
    __kind__: "trueFalse";
    trueFalse: boolean;
}): {
    multipleChoice: bigint;
} | {
    trueFalse: boolean;
} {
    return value.__kind__ === "multipleChoice" ? {
        multipleChoice: value.multipleChoice
    } : value.__kind__ === "trueFalse" ? {
        trueFalse: value.trueFalse
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "multipleChoice";
    multipleChoice: {
        correctOption: bigint;
        options: Array<string>;
    };
} | {
    __kind__: "trueFalse";
    trueFalse: {
        correctAnswer: boolean;
    };
}): {
    multipleChoice: {
        correctOption: bigint;
        options: Array<string>;
    };
} | {
    trueFalse: {
        correctAnswer: boolean;
    };
} {
    return value.__kind__ === "multipleChoice" ? {
        multipleChoice: value.multipleChoice
    } : value.__kind__ === "trueFalse" ? {
        trueFalse: value.trueFalse
    } : value;
}
function to_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Answer>): Array<_Answer> {
    return value.map((x)=>to_candid_Answer_n22(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
